version: "3.8"

services:

  db-pg-sportmate:
    container_name: db-pg-sportmate
    image: ${POSTGRES_IMG}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_SCHEMA}
    command: ["postgres", "-c", "wal_level=logical"]
    healthcheck:
      interval: 10s
      timeout: 30s
      retries: 3