spring:
  datasource:
    url: ${DATABASE_JDBC_URL:jdbc:postgresql://localhost:5432/sportmate}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${DATABASE_JDBC_URL:jdbc:postgresql://localhost:5432/sportmate}
    user: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

logging:
  level:
    root: INFO
    com.zaxxer.hikari: ERROR

server:
  port: ${PORT:8080}
