CREATE SEQUENCE IF NOT EXISTS HOBBIES_SEQ;
CREATE SEQUENCE IF NOT EXISTS SPORT_SEQ;
CREATE SEQUENCE IF NOT EXISTS USER_SEQ;
CREATE SEQUENCE IF NOT EXISTS ACTIVITY_SEQ;
CREATE SEQUENCE IF NOT EXISTS LEVEL_SEQ;