ALTER TABLE hobbies
    ALTER COLUMN id SET DEFAULT nextval('HOBBIES_SEQ');

ALTER TABLE sport
    ALTER COLUMN id SET DEFAULT nextval('SPORT_SEQ');

ALTER TABLE users
    ALTER COLUMN id SET DEFAULT nextval('USER_SEQ');

ALTER TABLE activity
    ALTER COLUMN id SET DEFAULT nextval('ACTIVITY_SEQ');

ALTER TABLE level
    ALTER COLUMN id SET DEFAULT nextval('LEVEL_SEQ');